#
#  Copyright © 2017 Bicycle (Sébastien BALARD)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http:#www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
inhibit_all_warnings!
use_frameworks!

# versions
#$rx_swift_version = '~> 4.2'

# logical pods groups
def pods_analytics
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Core'
end

def pods_rx
    pod 'RxSwift'#, $rx_swift_version
    pod 'RxCocoa'#, $rx_swift_version
    pod 'RxAlamofire'
    pod 'RxCoreLocation'
end

def pods_di
    pod 'Dip'#, '~> 6.1'
    pod 'Dip-UI'#, '~> 2.0'
end

def pods_io
    pod 'AlamofireObjectMapper'
end

def pods_widgets
    pod 'Toaster'
    pod 'Cluster'
    pod 'MaterialComponents/BottomSheet'
end

def pods_helpers
    #pod 'AlamofireActivityLogger'
    pod 'ReachabilitySwift'
end

# test logical pods groups
def pods_tests_rx
    pod 'RxSwift'#, $rx_swift_version
    pod 'RxBlocking'#, $rx_swift_version
    pod 'RxTest'#, $rx_swift_version
end

target 'Bicycle' do
    pods_analytics
    pods_rx
    pods_di
    pods_io
    pods_widgets
    pods_helpers
    pod 'SwiftyBeaver'

    target 'BicycleTests' do
        inherit! :search_paths
        pods_tests_rx
        pod 'Mockit', '~> 1.4'
    end

    target 'BicycleUITests' do
        inherit! :search_paths
        # Pods for testing
    end

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if config.name == 'Release'
                    config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule' # remove default warning on Xcode 9.4+
                else
                    config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                end
                config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO' # exclude pods of code coverage
            end
        end
    end
end
