#
#  Copyright © 2017 Bicycle (Sébastien BALARD)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http:#www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

platform :ios, '10.0'

target 'Bicycle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bicycle
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'XCGLogger'
  pod 'AlamofireObjectMapper'
  pod 'Cluster'
  pod 'Toaster'
  pod 'SearchTextField'
  pod 'RxSwift'
  pod 'RxCocoa'
  #pod 'RxMKMapView', :podspec => 'RxMKMapView.podspec'
  
  swift_32 = []
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          
          swift_version = '4.0'
          
          if swift_32.include?(target.name)
              swift_version = '3.2'
          end
          
          if swift_version
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = swift_version
              end
          end
      end
  end

  target 'BicycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BicycleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
