#
#  Copyright © 2017 Bicycle (Sébastien BALARD)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http:#www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

platform :ios, '10.0'

target 'Bicycle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bicycle
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'XCGLogger'
  pod 'AlamofireObjectMapper'
  pod 'Cluster'
  pod 'Toaster'
  pod 'SearchTextField'
  pod 'RxSwift'
  pod 'RxCocoa'
  #pod 'SearchTextField', '1.0.2'

  target 'BicycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BicycleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
